CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED_UART_MODE_INTERRUPT=y
CONFIG_ZMK_SPLIT_WIRED_HALF_DUPLEX_RX_TIMEOUT=20
CONFIG_ZMK_USB=n
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_KLOR_OMARCHY=y
