include:
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: klor_left
    artifact-name: klor-left-single-wire
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: klor_right
    artifact-name: klor-right-single-wire
